#include<iostream.h>
#include<conio.h>
#include<iomanip.h>
ostream &line(ostrem&out)
{
	cout<<"\n-------------------------\n";
	return out;
}
void main()
{
	clrscr();
	cout.self(ios::internal);
	cout.precisin(2);
	cout.fill('*');
	cout.width(8);
	cout<<-50.2587<<endl;
	cout<<(8);
	cout<<-156.6983
	cout.unself(ios::internal);
	cout.width(8);
	cout<<-14.458<<endl;
	getch();
}

