#include<stdio.h>
#include<conio.h>
void main()
{
	int a,b,c,d,e,f,g;
	clrscr();
	printf("\n Enter frist sub mark:");
	scanf("%d",&a);
	printf("\n enter second sub mark:");
	scanf("%d",&b);
	printf("\n enter third sub mark:");
	scanf("%d",&c);
	printf("\n enter fourth sub mark:");
	scanf("%d",&d);
	printf("\n enter fifth sub mark:");
	scanf("%D",&e);
	printf("\n enter sixth sub mark:");
	scanf("%d",&f);
	printf("\n enter sevanth sub mark:");
	scanf("%d",&g);



	printf("\n first sub mark is:%d",a);
	printf("\n second sub mark is:%d",b);
	printf("\n enter third sub mark is:%d",c);
	printf("\n enter fourth sub mark is:%d",d);
	printf("\n enter fifth sub mark is:%d",e);
	printf("\n enter sixth sub mark is:%d",f);
	printf("\n enter seventh sunb mark is:%d",g);
	getch();
}

