#include<stdio.h>
#include<conio.h>
#define size 5

void lsearch(int []);
void bsearch(int []);
void output(int []);
void ssort(int []);
void bsort(int []);
void msort(int [],int,int);
void mergesort(int [],int,int,int,int);
void qsort(int [],int,int);

void main()
{
	int i,a[size],ch;
	clrscr();
	for(i=0;i<=size-1;i++)
	{
		printf("Enter Number :");
		scanf("%d",&a[i]);
	}
	printf("\n\npress:\n m-
}
